project 'SwpExtensionDemo.xcodeproj'
# Uncomment the next line to define a global platform for your project


platform :ios, '10.0'

target 'SwpExtensionDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwpExtensionDemo

  pod 'SnapKit'

  pod 'SwpExtension/IntExtension', :path => '../'
  pod 'SwpExtension/FloatExtension', :path => '../'
  pod 'SwpExtension/DoubleExtension', :path => '../'
  pod 'SwpExtension/CGFloatExtension', :path => '../'
  pod 'SwpExtension/BundleExtension', :path => '../'
  pod 'SwpExtension/MD5Extension', :path => '../'
  pod 'SwpExtension/Base64Extension', :path => '../'
  pod 'SwpExtension/StringExtension', :path => '../'
  pod 'SwpExtension/UserDefaultsExtension', :path => '../'

  pod 'SwpExtension/UIViewExtension', :path => '../'
  pod 'SwpExtension/UIFontExtension', :path => '../'
  pod 'SwpExtension/UIColorExtension', :path => '../'
  pod 'SwpExtension/UIImageExtension', :path => '../'
  pod 'SwpExtension/UIScreenExtension', :path => '../'
  pod 'SwpExtension/UIButtonExtension', :path => '../'
  pod 'SwpExtension/UITextFieldExtension', :path => '../'
  pod 'SwpExtension/UINavigationExtension', :path => '../'
  
end
